### ISSUE TITLE
SourceList.EditDiff slow on no data change

### ISSUE THREAD

**Issue by Pinox** [reactiveui/DynamicData#256]
Working with SourceList<T>  if I do a SourceList<T>.EditDiff(T) with a data change from original source the editdiff function works perfectly.  However, If the edit data is exactly the same as the original data in the Sourcelist<T> then  I can see a visible update (refresh) on the screen and also a 1.5 second delay.  

Obviously if the EditDiff data is exactly the same as the original source you would except no screen refresh as nothing changed. This is not the case.

Working on latest version of DynamicData + ReactiveUI  + UWP
Windows 10 1903

**Comment by RolandPheasant** [comment]
Without reproducible code it is hard to comment on your scenario. To investigate further can you please create a broken unit test.

Also some more context may help. Are you using the equality comparer overload? does your object implement a custom hash code? Are the objects mutable? All these effect equality comparisons

**Comment by Pinox** [comment]
Hi @RolandPheasant, in luv with this lib btw, thks to u.

Please find link to repo , you will notice diffing the source with the same data is actually slower than clearing the source data and refilling it again.

[DynamicDataBug.zip](https://github.com/reactiveui/DynamicData/files/3444101/DynamicDataBug.zip)

**Comment by RolandPheasant** [comment]
The answer is very simple and this is not a bug. 

Naturally, EditDiff has do do more work than the standard clear and add range. The reason is it has to create a diff set between the original items and the new items provided.  To achieve this,  an equality comparer is used. In the case of your model you have not implemented equality on the Person model, nor have you passed have you passed an equality comparer (which is optional on the EditDiff method).  The effect of not using an equality comparer is that the method does not identify the new items and being the same as the old ones. This means 1) a diff set is created 2) all items are cleared 3) all new items are added.

The problem went away when I implemented equality on the person object as per [this gist](https://gist.github.com/RolandPheasant/e26ad64c16cdec31c813abfe0a907d64)

Equality is very important when items are contained in collection. I recommend all developers read [Eric Lippert's Guidelines and rules for GetHashCode](https://ericlippert.com/2011/02/28/guidelines-and-rules-for-gethashcode/).

**Comment by Pinox** [comment]
Thanks @RolandPheasant. Excuse the ignorance here, still trying to get my head around DD, definitely higher grade for me  ;))
