### ISSUE TITLE
The Edit method generates many notifications

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [reactiveui/DynamicData#353]
```C#
var sourceList = new SourceList<object>();
IObservableCollection<object> col = new ObservableCollectionExtended<object>();
sourceList.Connect().Bind(col).Subscribe();
int count = 0;
col.ObserveCollectionChanges().Subscribe(e =>
{
    count++;
});
            sourceList.Edit(internalList =>
            {
                internalList.Clear();
                internalList.AddRange(new List<object>() { new object(), new object(), new object() });
                internalList.AddRange(new List<object>() { new object(), new object(), new object() });
                internalList.AddRange(new List<object>() { new object(), new object(), new object() });
            });
            sourceList.Edit(internalList =>
            {
                internalList.Clear();
                internalList.AddRange(new List<object>() { new object(), new object(), new object() });
                internalList.AddRange(new List<object>() { new object(), new object(), new object() });
                internalList.AddRange(new List<object>() { new object(), new object(), new object() });
            });
```
Hi everyone, why in the code above, the number of notifications about a collection change is 11? As far as I read the documentation and it says that Edit guarantees the issuance of one notification?

How can I change the Source List so that only one notification is displayed in the linked collection?

**Comment by Claye-L** [comment]
Because the Edit action guarantees only one minimal ChangeSet is emitted through the pipeline. It does not guarantee that ObservableCollection gets only one change (because ObservableCollection is a base library type that simply can not represent all the changes to it in one single notification). It does ensure however that the ObervableCollection produces the minimal amount of changes necessary.

ObservableCollection only has one way too batch changes; the Reset action. This would recreate your whole UI. Instead DynamicData uses Add and Remove for each different element to ensure only the necessary elements of the UI are affected.

This is a desired effect and will not affect your app performance if that's your concern.


This behavior is fixed and unchangeable because ObservableCollection is used to interface Reactive ChangeSets with UI frameworks/components.

**Comment by AgPeHaJIuH1** [comment]
But can I somehow make SourceList generate Reset under certain conditions instead of many notifications?

**Comment by Claye-L** [comment]
Yes, the Bind operator has a resetThreshold overload that generate a batch Reset instead of incremental changes if the number of changes is greater than the threshold. 
.Bind(col,5) 
in your case this could generate 2 notifications only, at the cost of having to recreat the UI completely everytime. it's a tradeoff

**Comment by AgPeHaJIuH1** [comment]
I get it. Thank you so much! This will not help!
